env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/dev/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/dev/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/dev/fdm#password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "vault:eafdmmart/data/dev/fdm#driver"
  JWKS: "vault:eafdmmart/data/dev/fdm#jwks"
