env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/prod/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/prod/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/prod/fdm#password"
  GWURL: "vault:eafdmmart/data/prod/fdm#mapicurl"
  AUTHBASIC: "vault:eafdmmart/data/prod/fdm#mapicauth"
  TECHUSER: "vault:eafdmmart/data/prod/fdm#techuser"
  TECHPASSWORD: "vault:eafdmmart/data/prod/fdm#techpassword"


replicaCount: 1