env:
  SPRING_PROFILES_ACTIVE: test
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/test/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/test/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/test/fdm#password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "vault:eafdmmart/data/test/fdm#driver"
  JWKS: "vault:eafdmmart/data/test/fdm#jwks"
