env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/prod/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/prod/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/prod/fdm#password"
  INTEGRATION_PRODUCTS_SERVER_URL: "vault:eafdmmart/data/prod/fdm#productsserver"
  GWURL: "vault:eafdmmart/data/prod/fdm#mapicurl"
  AUTHBASIC: "vault:eafdmmart/data/prod/fdm#mapicauth"
  TECHUSER: "vault:eafdmmart/data/prod/fdm#techuser"
  TECHPASSWORD: "vault:eafdmmart/data/prod/fdm#techpassword"
  OTEL_EXPORTER_OTLP_ENDPOINT: "vault:eafdmmart/data/prod/fdm#opentelemetry"


replicaCount: 1

resources:
  limits:
    memory: 1500Mi
  requests:
    memory: 300Mi
